### ISSUE TITLE
ChartBench evaluation

### ISSUE THREAD

**Issue by zli999** [IDEA-FinAI/ChartMoE#4]
Hello! I wonder what metrics you have used in Table 3 for ChartBench: accp, npa, or the weighted sum of them?

**Comment by zli999** [comment]
Hello! I used your code to try ChartMoE. There is a bug about the vision encoder as follows:

Input image size (490*490) doesn't match model (336*336).

Could you please help to check your model and configuration? Thank you!

**Comment by Coobiw** [comment]
Hi, @zli999. Sorry, I have not encountered this problem. Please download the weights and configs on this huggingface link: [https://huggingface.co/IDEA-FinAI/chartmoe](https://huggingface.co/IDEA-FinAI/chartmoe). Then change your [ChartMOE_HF_PATH](https://github.com/Coobiw/ChartMoE/tree/master/chartmoe/utils/custom_path.py#L2) as shown in the README of this repo. 

If you can give me more details to reproduce your bug, that would be really better~. Thanks for you attention! If any question exists (like the version of some python package?), I'm very willing to communicate with you～!

**Comment by Coobiw** [comment]
As for the ChartBench result, both Acc+ and NQA are computed~

**Comment by zli999** [comment]
It works now! Thx! A great work!

**Comment by Coobiw** [comment]
Hi, @zli999 . #6 also encountered this problem. Can you share some details to solve it with @Lv996331209 and me? I will also add this bug into FAQs. Thanks for your help~
